### ISSUE TITLE
Assertion failed (m.dims >= 2) at erode

### ISSUE THREAD

**Issue by ghost** [opencv-java/object-detection#1]
Hi,

I was trying to run the code of the grabFrame method from the ObjRecognitionController class but I'm getting an error when I perform the Imgproc.erode operation:

Mat erodeElement = Imgproc.getStructuringElement(Imgproc.MORPH_RECT, new Size(12, 12));
Imgproc.erode(mask, morphOutput, erodeElement);

The error is:

OpenCV Error: Assertion failed (m.dims >= 2) in cv::Mat::Mat, file C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\core\src\matrix.cpp, line 454
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: C:\builds\master_PackSlaveAddon-win64-vc12-static\opencv\modules\core\src\matrix.cpp:454: error: (-215) m.dims >= 2 in function cv::Mat::Mat
]
    at org.opencv.imgproc.Imgproc.erode_2(Native Method)
    at org.opencv.imgproc.Imgproc.erode(Imgproc.java:2007)
    at MainMorphological.main(MainMorphological.java:34)

Have you had to deal with this error?do you know what the reason of the error is?

I don't know what the problem is since the mask and morphOutput elements are empty Mats and the erodeElement is exactly the same as the one you're using.

Thanks in advance.

**Comment by luigidr** [comment]
Hi,

I never encountered this error before... I can verify the code in the next days. eroWhat version of OpenCV (and Java) are you running? In which version of Windows are you working?

Notice, however, that `mask` should not be an empty `Mat`. In the `ObjRecognitionController` class, `mask` is filled by the code at line 203:

```
// threshold HSV image to select tennis balls
Core.inRange(hsvImage, minValues, maxValues, mask);
```

`mask` is the source image on which `erode()` works, it cannot be an "empty image".

**Comment by ghost** [comment]
Hi,

You are right, my problem was that the mask was an empty image. Since I was running a test and took only some pieces of your example I forgot to fill the mask. Now it's working fine.

Thanks a lot for your time.
